version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-octane-app
    container_name: laravel-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - redis
    environment:
      - OCTANE_SERVER=swoole
    command: php artisan octane:start --server=swoole --host=0.0.0.0 --port=8000
    env_file:
      - .env
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - app-network

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: solapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app-network

  queue-worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-octane-app
    container_name: queue-worker
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - .:/var/www
    command: php artisan queue:work --queue=default --sleep=3 --tries=3
    networks:
      - app-network

  supervisor:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-octane-app
    container_name: supervisor
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - .:/var/www
      - ./docker/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    command: /usr/bin/supervisord -n -c /etc/supervisor/conf.d/supervisord.conf
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge

